const deleteEmails = ["propertytree@propertytree.com",
    "rydegardens@pacificbmg.com.au",
    "hello@stackshare.io",
    "no-reply@snug.com",
    "news@comms.service.nsw.gov.au",
    "myaccount@optus.com.au",
    "noreply@github.com",
    "katieyu@alphapa.com.au",
    "shipment-tracking@amazon.com.au",
    "no-reply@getparceltracker.com",
    "service@paypal.com.au",
    "rydegardens@pacificbmg.com.au",
    "myaccount@optus.com.au",
    "account-security-noreply@accountprotection.microsoft.com"
    , "katieyu@alphapa.com.au",
    "messages-noreply@linkedin.com",
    "no-reply@virginactive.com.au",
    "qantasff@loyalty.qantas.com",
    "alumnirelations@dlsu.edu.ph",
    "noreply@steampowered.com",
    "microsoft-noreply@microsoft.com",
    "orders@culturekings.com.au",
    "no-reply@getparceltracker.com",
    "leasing@landpearl.com.au", "deliveroo",
    "network20",
    "telstra",
    "dlsu",
    "netflix",
    "virgin",
    "snug",
    "hyatt",
    "westpac",
    "hashicorp",
    "amazon",
    "aec",
    "airbnb",
    "apple",
    "analytics"]

module.exports = {
    deleteEmails
}