version: "3"

services:
  db:
    build: ./database
    container_name: db
    restart: always
    networks:
      - default
    volumes:
      - ./database/volumes/postgres10/data:/var/lib/postgresql/data
      - ./database/volumes/postgres10/backup:/var/lib/postgresql/backup
    ports:
      - ${DB_PORT:-5432}:5432
    env_file: ./configs/postgres.config
  db_hasura:
    image: hasura/graphql-engine:latest
    container_name: db_hasura
    depends_on:
      - db
    restart: always
    networks:
      - default
    command:
      - graphql-engine
      - serve
      - --enable-console
    ports:
      - ${HASURA_GRAPHQL_PORT:-18080}:8080
    env_file: ./configs/hasura.config

networks:
  default:
    external:
      name: main-network

volumes:
  pgadmin_data:
